### ISSUE TITLE
is there any news on this plugin?

### ISSUE THREAD

**Issue by Ravenclawer** [scaytrase/obsidian-alias-enricher#1]
I really like the idea of this plugin,is there any possibility that you will release this plugin?

**Comment by scaytrase** [comment]
@Ravenclawer hello, I'm not using obisdian for the moment, thus have no motivation to publish and support it officially. For my own usage it was possible to build plugin locally and install it to the local installation, so no release was needed

**Comment by Ravenclawer** [comment]
sorry, I don't have any background in programming, I just know how to install the  obsidian plugin in the following form, which includes three parts of files
![image](https://user-images.githubusercontent.com/73892411/195651252-3ac40607-4954-4bfc-b19e-d2a6a9e8008d.png), I will google how to do this but I think I am not gonna make it work (cry)

**Comment by scaytrase** [comment]
![image](https://user-images.githubusercontent.com/6578413/195653728-e3f9b393-8f2c-47d0-bf5c-faabec5e8ad0.png)

As far as I remember you need to turn off safe mode and put the plugin as folder into obsidian plugins folder

[main.zip](https://github.com/scaytrase/obsidian-alias-enricher/files/9778754/main.zip)

I've attached my last built `main.js`, put it into plugin folder (`plugins\obsidian-alias-enricher\main.js` where plugins is the dir given you by the folder button in the settings)

**Comment by Ravenclawer** [comment]
Thank you so much, it works like a charm, this plugin has so much potential,
![image](https://user-images.githubusercontent.com/73892411/195657121-b27ab90f-8b9d-427f-99b7-c25d86e89cae.png)
